name       : pixman
version    : 0.42.2
release    : 15
source     :
    - https://www.cairographics.org/releases/pixman-0.42.2.tar.gz : ea1480efada2fd948bc75366f7c349e1c96d3297d09a3fe62626e38e234a625e
license    : MIT
component  : desktop.library
summary    : pixman (software library for pixel manipulation)
description: |
    pixman is a low-level software library for pixel manipulation, providing features such as image compositing.
builddeps  :
    - pkgconfig32(libpng16)
optimize   : speed
emul32     : yes
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
